---
- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no
- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/
    copy=no
- name: restart apache
  service: name=httpd state=restarted
